### get token auth
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "password": "MySecretPas$word",
    "email": "vpupkin@yandex.ru"
}

### delete token auth
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: Token 654fa6eb7b0fdf8160968b9cedc1efd9171cabbd

{
    "password": "123456qwertY!!",
    "email": "test2"
}

### user registration
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "vpupkin@yandex.ru",
    "username": "EmailInUse",
    "first_name": "Email",
    "last_name": "InUse",
    "password": "MySecretPas$word"
}

### get users list
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json

### get users list with limit
GET http://127.0.0.1:8000/api/users/?limit=1
Content-Type: application/json

### get users list with page
GET http://127.0.0.1:8000/api/users/?page=1
Content-Type: application/json

### profile user
GET http://127.0.0.1:8000/api/users/1/
Content-Type: application/json


### get current user
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### set passworc
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 1ff3793e8ea6a0ade3641253e4c2a996ca10167e

{
  "new_password": "123456qwertY!!",
  "current_password": "123456qwertY!!"
}

### subscribe on user
POST http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765



### unsubscribe on user
DELETE http://127.0.0.1:8000/api/users/2/subscribe/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765 # test
#Authorization: Token 7dda1a9f4e5bc8b08f36da4aeb39fc03c4802f94 # test4

### get list subscribtions
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### get tags
GET http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### get tag
GET http://127.0.0.1:8000/api/tags/1/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### get ingredients
GET http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json
Authorization: Token 240e5ebe82e63fc48c4d8453bfd6d06ad1255fd3

### get ingredients by name
GET http://127.0.0.1:8000/api/ingredients/?name=Я
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### get detail ingredient
GET http://127.0.0.1:8000/api/ingredients/1/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### create recipe
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9f172b8fa13a85459861d78af045828ad5a77736

{
  "ingredients": [
    {
      "id": 1195,
      "amount": 10
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Рецепт 1",
  "text": "Описание рецепта 1",
  "cooking_time": 1
}

### get recipes
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json


### get recipes with limit
GET http://127.0.0.1:8000/api/recipes/?limit=2
Content-Type: application/json

### get recipes by author
GET http://127.0.0.1:8000/api/recipes/?author=47
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765


### get detail recipe
GET http://127.0.0.1:8000/api/recipes/148/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### update full recipe
PATCH http://127.0.0.1:8000/api/recipes/162/
Content-Type: application/json
Authorization: Token 9f172b8fa13a85459861d78af045828ad5a77736

{
  "ingredients": [
    {
      "id": 1,
      "amount": 25
    }
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Рецепт обновление",
  "text": "Описание рецепта обновление",
  "cooking_time": 2
}

### delete recipe
DELETE http://127.0.0.1:8000/api/recipes/147/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### added recipe to favorite
POST http://127.0.0.1:8000/api/recipes/148/favorite/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### delete recipe from favorite
DELETE http://127.0.0.1:8000/api/recipes/148/favorite/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### added recipe to shopping cart
POST http://127.0.0.1:8000/api/recipes/149/shopping_cart/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### remove recipe from shopping cart
DELETE http://127.0.0.1:8000/api/recipes/148/shopping_cart/
Content-Type: application/json
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765

### download from shopping cart
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token ca091311bf78bf0fd5d32dde2cfaa35f054a3765