### get token auth
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "password": "3385105aq",
    "username": "test"
}

### user registration
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "test@ya.ru",
  "username": "test3",
  "first_name": "testname1",
  "last_name": "lastname1",
  "password": "123456qwertY"
}

### get users list
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: Token 1799e42461e167bd7d001e08e650eca169f8d308

### get current user
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 1799e42461e167bd7d001e08e650eca169f8d308
